name: Build and publish TheMulti0.Console

on:
  workflow_dispatch:
  push:
    paths:
      - "TheMulti0.Console/**"
  pull_request:
    paths:
      - "TheMulti0.Console/**"

env:
  DOTNET_VERSION: 5.0.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore TheMulti0.Console
      
    - name: Build
      run: dotnet build --no-restore TheMulti0.Console

  publish:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Publish on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: TheMulti0.Console/TheMulti0.Console.csproj
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        TAG_COMMIT: false